### ISSUE TITLE
Can it work in Android phone? 

### ISSUE THREAD

**Issue by ahadrox** [Topherick/FREEBITCO.IN#1]

**Comment by Topherick** [comment]
Nope

**Comment by michaelgabriel** [comment]
How to get 1.0000000 in freebitco.in in one day assuming that I have already account?

**Comment by AlferazEvans** [comment]
Hello everyone, friends, please help me how to get 10,000 rolls? I lost everything 0.02460841satoshi
![Снимок PNG55](https://user-images.githubusercontent.com/47814434/120373238-ebb51f00-c339-11eb-8035-cd10736a7548.PNG)

**Comment by AlferazEvans** [comment]
Hello everyone, friends, please help me how to get 10,000 rolls? I lost everything 0.02460841satoshi
![Снимок PNG55](https://user-images.githubusercontent.com/47814434/120373389.PNG)

**Comment by AlferazEvans** [comment]
Hello everyone, friends, please help me how to get 10,000 rolls? I lost everything 0.02460841satoshi
![Снимок PNG55](https://user-images.githubusercontent.com/47814434/120373525-43ec2100-c33a-11eb-8b1e-3f24eacb78ef.PNG)

**Comment by michaelgabriel** [comment]
You have to decrypt your email.
